import type { Metadata } from "next";
import "./globals.css";
import Navbar from "./components/Nav/navbar";
import localFont from 'next/font/local';

const gwangwon = localFont({
  src: './fonts/GwangwonEduPower.woff',
  variable: '--font-gwangwon',
});


export const metadata: Metadata = {
  title: "INFOTEAM BLOG",
  description: "Generated by Jinseo",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html className={gwangwon.variable}>
      
      <body className="flex flex-col items-center py-[100px]">
        <Navbar/>
        <div style={{ height: "72px" }}></div>"
        <main className="w-[900px]">{children}</main>
        
      </body>
    </html>
  );
}
